[package]
name = "asgard"
version = "0.1.0"
authors = ["Christian Lavoie <clavoie@sandreckoning.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.5"
pest = "2.1.3"
pest_derive = "2.1.0"
rustyline = "6.2.0"
